using Figures;
Console.WriteLine("Введите сторону а: ");
Square sq = new Square(double.Parse(Console.ReadLine()));
sq.Actions();
Console.WriteLine("Введите стороны а и b: ");
Straight_Square st_sq = new Straight_Square(double.Parse(Console.ReadLine()), double.Parse(Console.ReadLine()));
st_sq.Actions();
Console.WriteLine("Введите стороны а, b и с: ");
Triangle tr = new Triangle(double.Parse(Console.ReadLine()), double.Parse(Console.ReadLine()), double.Parse(Console.ReadLine()));
tr.Actions();
Console.WriteLine("Введите радиус круга: ");
Circle cr = new Circle(double.Parse(Console.ReadLine()));
cr.Actions();
Console.WriteLine("Введите основание и боковое ребро правильной пирамиды: ");
Pyramide pr = new Pyramide(double.Parse(Console.ReadLine()), double.Parse(Console.ReadLine()));
pr.Actions();
Console.WriteLine("Введите радиус и высоту конуса:");
Cone cn = new Cone(double.Parse(Console.ReadLine()), double.Parse(Console.ReadLine()));
cn.Actions();
Console.WriteLine("Введите основание и боковое ребро треугольной пирамиды: ");
Triangle_Pyramide tr_pr = new Triangle_Pyramide(double.Parse(Console.ReadLine()), double.Parse(Console.ReadLine()));
tr_pr.Actions();